<?php require base_path('.dalt/resources/views/layouts/head.php') ?>
<?php require base_path('.dalt/resources/views/layouts/learn-nav.php') ?>
<?php $completedCount = count(array_filter($lessons, fn (array $lesson): bool => isset($completedLessonIds[$lesson['id']]))); $totalLessons = count($lessons); ?>
<main class="min-h-[calc(100vh-8rem)] bg-[#0a0d12] text-gray-300" id="app" tabindex="-1">
  <div class="mx-auto max-w-3xl px-5 py-10 sm:px-6 sm:py-16">
    <a href="/learn" class="inline-flex items-center text-sm font-medium text-gray-500 transition-colors hover:text-[#93DA97]"><span class="mr-2" aria-hidden="true">←</span>Learning dashboard</a>
    <header class="mt-10 border-b border-[#1e293b] pb-10">
      <p class="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-[#93DA97]">Learning path</p>
      <h1 class="mt-4 text-4xl font-bold tracking-tight text-gray-50 sm:text-5xl"><?= htmlspecialchars($section['title']) ?></h1>
      <p class="mt-5 max-w-2xl text-lg leading-8 text-gray-400"><?= htmlspecialchars($section['description']) ?></p>
      <div class="mt-8 flex flex-wrap items-center gap-5"><p class="font-mono text-sm text-gray-400"><?= $completedCount ?> of <?= $totalLessons ?> lessons completed</p><?php if ($nextLesson !== null): ?><a href="/learn/lessons/<?= $nextLesson['id'] ?>" class="inline-flex items-center rounded-lg bg-[#93DA97] px-4 py-2.5 text-sm font-bold text-[#0a0d12] transition-colors hover:bg-[#b5edb8]">Continue <?= htmlspecialchars($section['title']) ?> <span class="ml-2" aria-hidden="true">→</span></a><?php endif; ?></div>
    </header>
    <section class="mt-12" aria-labelledby="path-sequence-title"><h2 id="path-sequence-title" class="text-2xl font-bold text-gray-100">Your <?= htmlspecialchars($section['title']) ?> path</h2><ol class="mt-6 divide-y divide-[#1e293b] border-y border-[#1e293b]"><?php foreach ($lessons as $lesson): ?><?php $completed = isset($completedLessonIds[$lesson['id']]); $next = $nextLesson !== null && $nextLesson['id'] === $lesson['id']; ?><li><a href="/learn/lessons/<?= $lesson['id'] ?>" class="group grid gap-3 py-6 sm:grid-cols-[2rem_1fr_auto] sm:items-start sm:gap-5"><span class="flex h-8 w-8 items-center justify-center rounded-full border <?= $completed ? 'border-[#93DA97]/40 bg-[#93DA97]/10 text-[#93DA97]' : ($next ? 'border-[#93DA97]/50 text-[#93DA97]' : 'border-gray-700 text-gray-500') ?> font-mono text-sm"><?= $completed ? '✓' : ($next ? '→' : '○') ?></span><span><span class="block font-semibold text-gray-200 group-hover:text-[#93DA97]"><?= htmlspecialchars($lesson['title']) ?></span><span class="mt-1 block text-sm leading-6 text-gray-500"><?= htmlspecialchars($lesson['description']) ?></span><?php if ($next): ?><span class="mt-3 block text-sm font-medium text-[#93DA97]">Next recommended</span><?php endif; ?></span><span class="font-mono text-xs text-gray-500"><?= $section['title'] ?> · <?= $lesson['section_order'] ?> of <?= $totalLessons ?></span></a></li><?php endforeach; ?></ol></section>
    <?php if ($recommendedKnowledge !== []): ?><aside class="mt-12 border-t border-[#1e293b] pt-8" aria-labelledby="knowledge-title"><h2 id="knowledge-title" class="text-lg font-bold text-gray-100">Recommended knowledge</h2><p class="mt-1 text-sm leading-6 text-gray-500">These topics may make this path easier. You can still start <?= htmlspecialchars($section['title']) ?> now.</p><ul class="mt-5 divide-y divide-[#1e293b] border-y border-[#1e293b]"><?php foreach ($recommendedKnowledge as $lesson): ?><li class="flex items-center justify-between gap-4 py-4"><a href="/learn/lessons/<?= $lesson['id'] ?>" class="font-medium text-gray-300 hover:text-[#93DA97]"><?= htmlspecialchars($lesson['title']) ?></a><span class="text-sm <?= isset($completedLessonIds[$lesson['id']]) ? 'text-[#93DA97]' : 'text-gray-500' ?>"><?= isset($completedLessonIds[$lesson['id']]) ? 'Completed ✓' : 'Not completed' ?></span></li><?php endforeach; ?></ul></aside><?php endif; ?>
  </div>
</main>
<?php require base_path('.dalt/resources/views/layouts/learn-end.php') ?>
